Added a check that the 'jar' command can be found ok.

diff --git a/mkjar b/mkjar
--- a/mkjar
+++ b/mkjar
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+`which jar &> /dev/null`
+cmdstatus=$?
+
+if [ "$cmdstatus" == "1" ]; then
+   echo "The 'jar' command could not be found. Make sure it is installed and in your path."
+   exit
+fi 
+
 filename="simulator.jar"
 if [ "$1" != "" ]; then
    filename=$1
